
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(128) candidate7(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nchw) {
  float conv2d_nchw_local[8];
  __shared__ float pad_temp_shared[64];
  __shared__ float kernel_shared[4096];
  conv2d_nchw_local[0] = 0.000000e+00f;
  conv2d_nchw_local[1] = 0.000000e+00f;
  conv2d_nchw_local[2] = 0.000000e+00f;
  conv2d_nchw_local[3] = 0.000000e+00f;
  conv2d_nchw_local[4] = 0.000000e+00f;
  conv2d_nchw_local[5] = 0.000000e+00f;
  conv2d_nchw_local[6] = 0.000000e+00f;
  conv2d_nchw_local[7] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 64; ++rc_outer_outer) {
    __syncthreads();
    if (((int)threadIdx.x) < 64) {
      pad_temp_shared[((int)threadIdx.x)] = data[((((((rc_outer_outer * 3136) + ((((int)threadIdx.x) >> 2) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + (((((int)threadIdx.x) & 3) >> 1) * 14)) + ((((int)blockIdx.x) % 7) * 2)) + (((int)threadIdx.x) & 1))];
    }
    kernel_shared[((int)threadIdx.x)] = kernel[(((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15))];
    kernel_shared[(((int)threadIdx.x) + 128)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 8192)];
    kernel_shared[(((int)threadIdx.x) + 256)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 16384)];
    kernel_shared[(((int)threadIdx.x) + 384)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 24576)];
    kernel_shared[(((int)threadIdx.x) + 512)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 32768)];
    kernel_shared[(((int)threadIdx.x) + 640)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 40960)];
    kernel_shared[(((int)threadIdx.x) + 768)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 49152)];
    kernel_shared[(((int)threadIdx.x) + 896)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 57344)];
    kernel_shared[(((int)threadIdx.x) + 1024)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 65536)];
    kernel_shared[(((int)threadIdx.x) + 1152)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 73728)];
    kernel_shared[(((int)threadIdx.x) + 1280)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 81920)];
    kernel_shared[(((int)threadIdx.x) + 1408)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 90112)];
    kernel_shared[(((int)threadIdx.x) + 1536)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 98304)];
    kernel_shared[(((int)threadIdx.x) + 1664)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 106496)];
    kernel_shared[(((int)threadIdx.x) + 1792)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 114688)];
    kernel_shared[(((int)threadIdx.x) + 1920)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 122880)];
    kernel_shared[(((int)threadIdx.x) + 2048)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 131072)];
    kernel_shared[(((int)threadIdx.x) + 2176)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 139264)];
    kernel_shared[(((int)threadIdx.x) + 2304)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 147456)];
    kernel_shared[(((int)threadIdx.x) + 2432)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 155648)];
    kernel_shared[(((int)threadIdx.x) + 2560)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 163840)];
    kernel_shared[(((int)threadIdx.x) + 2688)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 172032)];
    kernel_shared[(((int)threadIdx.x) + 2816)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 180224)];
    kernel_shared[(((int)threadIdx.x) + 2944)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 188416)];
    kernel_shared[(((int)threadIdx.x) + 3072)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 196608)];
    kernel_shared[(((int)threadIdx.x) + 3200)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 204800)];
    kernel_shared[(((int)threadIdx.x) + 3328)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 212992)];
    kernel_shared[(((int)threadIdx.x) + 3456)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 221184)];
    kernel_shared[(((int)threadIdx.x) + 3584)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 229376)];
    kernel_shared[(((int)threadIdx.x) + 3712)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 237568)];
    kernel_shared[(((int)threadIdx.x) + 3840)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 245760)];
    kernel_shared[(((int)threadIdx.x) + 3968)] = kernel[((((((((int)blockIdx.x) / 49) * 262144) + ((((int)threadIdx.x) >> 4) * 1024)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 253952)];
    __syncthreads();
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[0] * kernel_shared[(((int)threadIdx.x) * 16)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[1] * kernel_shared[(((int)threadIdx.x) * 16)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[2] * kernel_shared[(((int)threadIdx.x) * 16)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[3] * kernel_shared[(((int)threadIdx.x) * 16)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[0] * kernel_shared[((((int)threadIdx.x) * 16) + 2048)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[1] * kernel_shared[((((int)threadIdx.x) * 16) + 2048)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[2] * kernel_shared[((((int)threadIdx.x) * 16) + 2048)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[3] * kernel_shared[((((int)threadIdx.x) * 16) + 2048)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[4] * kernel_shared[((((int)threadIdx.x) * 16) + 1)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[5] * kernel_shared[((((int)threadIdx.x) * 16) + 1)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[6] * kernel_shared[((((int)threadIdx.x) * 16) + 1)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[7] * kernel_shared[((((int)threadIdx.x) * 16) + 1)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[4] * kernel_shared[((((int)threadIdx.x) * 16) + 2049)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[5] * kernel_shared[((((int)threadIdx.x) * 16) + 2049)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[6] * kernel_shared[((((int)threadIdx.x) * 16) + 2049)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[7] * kernel_shared[((((int)threadIdx.x) * 16) + 2049)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[8] * kernel_shared[((((int)threadIdx.x) * 16) + 2)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[9] * kernel_shared[((((int)threadIdx.x) * 16) + 2)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[10] * kernel_shared[((((int)threadIdx.x) * 16) + 2)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[11] * kernel_shared[((((int)threadIdx.x) * 16) + 2)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[8] * kernel_shared[((((int)threadIdx.x) * 16) + 2050)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[9] * kernel_shared[((((int)threadIdx.x) * 16) + 2050)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[10] * kernel_shared[((((int)threadIdx.x) * 16) + 2050)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[11] * kernel_shared[((((int)threadIdx.x) * 16) + 2050)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[12] * kernel_shared[((((int)threadIdx.x) * 16) + 3)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[13] * kernel_shared[((((int)threadIdx.x) * 16) + 3)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[14] * kernel_shared[((((int)threadIdx.x) * 16) + 3)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[15] * kernel_shared[((((int)threadIdx.x) * 16) + 3)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[12] * kernel_shared[((((int)threadIdx.x) * 16) + 2051)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[13] * kernel_shared[((((int)threadIdx.x) * 16) + 2051)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[14] * kernel_shared[((((int)threadIdx.x) * 16) + 2051)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[15] * kernel_shared[((((int)threadIdx.x) * 16) + 2051)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[16] * kernel_shared[((((int)threadIdx.x) * 16) + 4)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[17] * kernel_shared[((((int)threadIdx.x) * 16) + 4)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[18] * kernel_shared[((((int)threadIdx.x) * 16) + 4)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[19] * kernel_shared[((((int)threadIdx.x) * 16) + 4)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[16] * kernel_shared[((((int)threadIdx.x) * 16) + 2052)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[17] * kernel_shared[((((int)threadIdx.x) * 16) + 2052)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[18] * kernel_shared[((((int)threadIdx.x) * 16) + 2052)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[19] * kernel_shared[((((int)threadIdx.x) * 16) + 2052)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[20] * kernel_shared[((((int)threadIdx.x) * 16) + 5)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[21] * kernel_shared[((((int)threadIdx.x) * 16) + 5)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[22] * kernel_shared[((((int)threadIdx.x) * 16) + 5)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[23] * kernel_shared[((((int)threadIdx.x) * 16) + 5)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[20] * kernel_shared[((((int)threadIdx.x) * 16) + 2053)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[21] * kernel_shared[((((int)threadIdx.x) * 16) + 2053)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[22] * kernel_shared[((((int)threadIdx.x) * 16) + 2053)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[23] * kernel_shared[((((int)threadIdx.x) * 16) + 2053)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[24] * kernel_shared[((((int)threadIdx.x) * 16) + 6)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[25] * kernel_shared[((((int)threadIdx.x) * 16) + 6)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[26] * kernel_shared[((((int)threadIdx.x) * 16) + 6)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[27] * kernel_shared[((((int)threadIdx.x) * 16) + 6)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[24] * kernel_shared[((((int)threadIdx.x) * 16) + 2054)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[25] * kernel_shared[((((int)threadIdx.x) * 16) + 2054)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[26] * kernel_shared[((((int)threadIdx.x) * 16) + 2054)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[27] * kernel_shared[((((int)threadIdx.x) * 16) + 2054)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[28] * kernel_shared[((((int)threadIdx.x) * 16) + 7)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[29] * kernel_shared[((((int)threadIdx.x) * 16) + 7)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[30] * kernel_shared[((((int)threadIdx.x) * 16) + 7)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[31] * kernel_shared[((((int)threadIdx.x) * 16) + 7)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[28] * kernel_shared[((((int)threadIdx.x) * 16) + 2055)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[29] * kernel_shared[((((int)threadIdx.x) * 16) + 2055)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[30] * kernel_shared[((((int)threadIdx.x) * 16) + 2055)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[31] * kernel_shared[((((int)threadIdx.x) * 16) + 2055)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[32] * kernel_shared[((((int)threadIdx.x) * 16) + 8)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[33] * kernel_shared[((((int)threadIdx.x) * 16) + 8)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[34] * kernel_shared[((((int)threadIdx.x) * 16) + 8)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[35] * kernel_shared[((((int)threadIdx.x) * 16) + 8)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[32] * kernel_shared[((((int)threadIdx.x) * 16) + 2056)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[33] * kernel_shared[((((int)threadIdx.x) * 16) + 2056)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[34] * kernel_shared[((((int)threadIdx.x) * 16) + 2056)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[35] * kernel_shared[((((int)threadIdx.x) * 16) + 2056)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[36] * kernel_shared[((((int)threadIdx.x) * 16) + 9)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[37] * kernel_shared[((((int)threadIdx.x) * 16) + 9)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[38] * kernel_shared[((((int)threadIdx.x) * 16) + 9)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[39] * kernel_shared[((((int)threadIdx.x) * 16) + 9)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[36] * kernel_shared[((((int)threadIdx.x) * 16) + 2057)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[37] * kernel_shared[((((int)threadIdx.x) * 16) + 2057)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[38] * kernel_shared[((((int)threadIdx.x) * 16) + 2057)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[39] * kernel_shared[((((int)threadIdx.x) * 16) + 2057)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[40] * kernel_shared[((((int)threadIdx.x) * 16) + 10)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[41] * kernel_shared[((((int)threadIdx.x) * 16) + 10)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[42] * kernel_shared[((((int)threadIdx.x) * 16) + 10)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[43] * kernel_shared[((((int)threadIdx.x) * 16) + 10)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[40] * kernel_shared[((((int)threadIdx.x) * 16) + 2058)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[41] * kernel_shared[((((int)threadIdx.x) * 16) + 2058)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[42] * kernel_shared[((((int)threadIdx.x) * 16) + 2058)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[43] * kernel_shared[((((int)threadIdx.x) * 16) + 2058)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[44] * kernel_shared[((((int)threadIdx.x) * 16) + 11)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[45] * kernel_shared[((((int)threadIdx.x) * 16) + 11)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[46] * kernel_shared[((((int)threadIdx.x) * 16) + 11)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[47] * kernel_shared[((((int)threadIdx.x) * 16) + 11)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[44] * kernel_shared[((((int)threadIdx.x) * 16) + 2059)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[45] * kernel_shared[((((int)threadIdx.x) * 16) + 2059)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[46] * kernel_shared[((((int)threadIdx.x) * 16) + 2059)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[47] * kernel_shared[((((int)threadIdx.x) * 16) + 2059)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[48] * kernel_shared[((((int)threadIdx.x) * 16) + 12)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[49] * kernel_shared[((((int)threadIdx.x) * 16) + 12)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[50] * kernel_shared[((((int)threadIdx.x) * 16) + 12)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[51] * kernel_shared[((((int)threadIdx.x) * 16) + 12)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[48] * kernel_shared[((((int)threadIdx.x) * 16) + 2060)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[49] * kernel_shared[((((int)threadIdx.x) * 16) + 2060)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[50] * kernel_shared[((((int)threadIdx.x) * 16) + 2060)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[51] * kernel_shared[((((int)threadIdx.x) * 16) + 2060)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[52] * kernel_shared[((((int)threadIdx.x) * 16) + 13)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[53] * kernel_shared[((((int)threadIdx.x) * 16) + 13)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[54] * kernel_shared[((((int)threadIdx.x) * 16) + 13)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[55] * kernel_shared[((((int)threadIdx.x) * 16) + 13)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[52] * kernel_shared[((((int)threadIdx.x) * 16) + 2061)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[53] * kernel_shared[((((int)threadIdx.x) * 16) + 2061)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[54] * kernel_shared[((((int)threadIdx.x) * 16) + 2061)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[55] * kernel_shared[((((int)threadIdx.x) * 16) + 2061)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[56] * kernel_shared[((((int)threadIdx.x) * 16) + 14)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[57] * kernel_shared[((((int)threadIdx.x) * 16) + 14)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[58] * kernel_shared[((((int)threadIdx.x) * 16) + 14)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[59] * kernel_shared[((((int)threadIdx.x) * 16) + 14)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[56] * kernel_shared[((((int)threadIdx.x) * 16) + 2062)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[57] * kernel_shared[((((int)threadIdx.x) * 16) + 2062)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[58] * kernel_shared[((((int)threadIdx.x) * 16) + 2062)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[59] * kernel_shared[((((int)threadIdx.x) * 16) + 2062)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[60] * kernel_shared[((((int)threadIdx.x) * 16) + 15)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[61] * kernel_shared[((((int)threadIdx.x) * 16) + 15)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[62] * kernel_shared[((((int)threadIdx.x) * 16) + 15)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[63] * kernel_shared[((((int)threadIdx.x) * 16) + 15)]));
    conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[60] * kernel_shared[((((int)threadIdx.x) * 16) + 2063)]));
    conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[61] * kernel_shared[((((int)threadIdx.x) * 16) + 2063)]));
    conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[62] * kernel_shared[((((int)threadIdx.x) * 16) + 2063)]));
    conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[63] * kernel_shared[((((int)threadIdx.x) * 16) + 2063)]));
  }
  conv2d_nchw[(((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2))] = conv2d_nchw_local[0];
  conv2d_nchw[((((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2)) + 1)] = conv2d_nchw_local[1];
  conv2d_nchw[((((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2)) + 14)] = conv2d_nchw_local[2];
  conv2d_nchw[((((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2)) + 15)] = conv2d_nchw_local[3];
  conv2d_nchw[((((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2)) + 25088)] = conv2d_nchw_local[4];
  conv2d_nchw[((((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2)) + 25089)] = conv2d_nchw_local[5];
  conv2d_nchw[((((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2)) + 25102)] = conv2d_nchw_local[6];
  conv2d_nchw[((((((((int)blockIdx.x) / 49) * 50176) + (((int)threadIdx.x) * 196)) + (((((int)blockIdx.x) % 49) / 7) * 28)) + ((((int)blockIdx.x) % 7) * 2)) + 25103)] = conv2d_nchw_local[7];
}


