
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(512) candidate0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nchw) {
  float conv2d_nchw_local[16];
  __shared__ float pad_temp_shared[1440];
  __shared__ float kernel_shared[4608];
  conv2d_nchw_local[0] = 0.000000e+00f;
  conv2d_nchw_local[1] = 0.000000e+00f;
  conv2d_nchw_local[2] = 0.000000e+00f;
  conv2d_nchw_local[3] = 0.000000e+00f;
  conv2d_nchw_local[4] = 0.000000e+00f;
  conv2d_nchw_local[5] = 0.000000e+00f;
  conv2d_nchw_local[6] = 0.000000e+00f;
  conv2d_nchw_local[7] = 0.000000e+00f;
  conv2d_nchw_local[8] = 0.000000e+00f;
  conv2d_nchw_local[9] = 0.000000e+00f;
  conv2d_nchw_local[10] = 0.000000e+00f;
  conv2d_nchw_local[11] = 0.000000e+00f;
  conv2d_nchw_local[12] = 0.000000e+00f;
  conv2d_nchw_local[13] = 0.000000e+00f;
  conv2d_nchw_local[14] = 0.000000e+00f;
  conv2d_nchw_local[15] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 8; ++rc_outer_outer) {
    __syncthreads();
    if (((int)threadIdx.x) < 480) {
      pad_temp_shared[(((int)threadIdx.x) * 3)] = ((((1 <= (((((int)blockIdx.x) / 14) * 8) + ((((int)threadIdx.x) % 60) / 6))) && ((((((int)blockIdx.x) / 14) * 8) + ((((int)threadIdx.x) % 60) / 6)) < 225)) && (1 <= (((((int)blockIdx.x) % 14) * 16) + ((((int)threadIdx.x) % 6) * 3)))) ? data[(((((((rc_outer_outer * 401408) + ((((int)threadIdx.x) / 60) * 50176)) + ((((int)blockIdx.x) / 14) * 1792)) + (((((int)threadIdx.x) % 60) / 6) * 224)) + ((((int)blockIdx.x) % 14) * 16)) + ((((int)threadIdx.x) % 6) * 3)) - 225)] : 0.000000e+00f);
      pad_temp_shared[((((int)threadIdx.x) * 3) + 1)] = (((1 <= (((((int)blockIdx.x) / 14) * 8) + ((((int)threadIdx.x) % 60) / 6))) && ((((((int)blockIdx.x) / 14) * 8) + ((((int)threadIdx.x) % 60) / 6)) < 225)) ? data[(((((((rc_outer_outer * 401408) + ((((int)threadIdx.x) / 60) * 50176)) + ((((int)blockIdx.x) / 14) * 1792)) + (((((int)threadIdx.x) % 60) / 6) * 224)) + ((((int)blockIdx.x) % 14) * 16)) + ((((int)threadIdx.x) % 6) * 3)) - 224)] : 0.000000e+00f);
      pad_temp_shared[((((int)threadIdx.x) * 3) + 2)] = ((((1 <= (((((int)blockIdx.x) / 14) * 8) + ((((int)threadIdx.x) % 60) / 6))) && ((((((int)blockIdx.x) / 14) * 8) + ((((int)threadIdx.x) % 60) / 6)) < 225)) && ((((((int)blockIdx.x) % 14) * 16) + ((((int)threadIdx.x) % 6) * 3)) < 223)) ? data[(((((((rc_outer_outer * 401408) + ((((int)threadIdx.x) / 60) * 50176)) + ((((int)blockIdx.x) / 14) * 1792)) + (((((int)threadIdx.x) % 60) / 6) * 224)) + ((((int)blockIdx.x) % 14) * 16)) + ((((int)threadIdx.x) % 6) * 3)) - 223)] : 0.000000e+00f);
    }
    *(float3*)(kernel_shared + (((int)threadIdx.x) * 3)) = *(float3*)(kernel + ((((((int)threadIdx.x) / 24) * 576) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) % 24) * 3)));
    *(float3*)(kernel_shared + ((((int)threadIdx.x) * 3) + 1536)) = *(float3*)(kernel + (((((((int)threadIdx.x) + 512) / 24) * 576) + (rc_outer_outer * 72)) + (((((int)threadIdx.x) + 8) % 24) * 3)));
    *(float3*)(kernel_shared + ((((int)threadIdx.x) * 3) + 3072)) = *(float3*)(kernel + (((((((int)threadIdx.x) + 1024) / 24) * 576) + (rc_outer_outer * 72)) + (((((int)threadIdx.x) + 16) % 24) * 3)));
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 2; ++rc_outer_inner) {
      for (int ff_c_outer_inner = 0; ff_c_outer_inner < 4; ++ff_c_outer_inner) {
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[(((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2))] * kernel_shared[((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36))]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 1)] * kernel_shared[((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36))]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 18)] * kernel_shared[((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36))]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 19)] * kernel_shared[((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36))]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 1)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 1)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 2)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 1)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 19)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 1)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 20)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 1)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 2)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 2)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 3)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 2)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 20)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 2)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 21)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 2)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 18)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 3)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 19)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 3)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 36)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 3)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 37)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 3)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 19)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 4)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 20)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 4)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 37)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 4)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 38)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 4)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 20)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 5)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 21)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 5)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 38)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 5)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 39)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 5)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 36)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 6)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 37)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 6)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 54)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 6)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 55)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 6)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 37)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 7)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 38)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 7)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 55)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 7)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 56)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 7)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 38)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 8)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 39)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 8)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 56)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 8)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 57)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 8)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 180)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 9)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 181)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 9)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 198)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 9)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 199)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 9)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 181)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 10)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 182)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 10)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 199)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 10)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 200)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 10)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 182)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 11)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 183)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 11)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 200)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 11)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 201)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 11)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 198)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 12)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 199)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 12)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 216)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 12)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 217)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 12)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 199)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 13)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 200)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 13)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 217)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 13)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 218)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 13)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 200)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 14)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 201)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 14)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 218)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 14)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 219)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 14)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 216)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 15)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 217)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 15)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 234)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 15)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 235)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 15)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 217)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 16)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 218)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 16)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 235)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 16)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 236)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 16)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 218)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 17)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 219)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 17)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 236)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 17)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 237)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 17)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 360)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 18)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 361)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 18)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 378)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 18)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 379)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 18)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 361)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 19)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 362)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 19)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 379)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 19)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 380)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 19)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 362)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 20)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 363)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 20)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 380)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 20)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 381)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 20)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 378)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 21)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 379)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 21)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 396)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 21)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 397)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 21)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 379)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 22)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 380)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 22)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 397)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 22)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 398)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 22)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 380)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 23)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 381)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 23)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 398)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 23)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 399)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 23)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 396)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 24)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 397)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 24)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 414)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 24)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 415)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 24)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 397)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 25)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 398)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 25)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 415)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 25)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 416)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 25)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 398)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 26)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 399)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 26)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 416)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 26)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 417)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 26)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 540)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 27)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 541)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 27)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 558)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 27)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 559)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 27)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 541)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 28)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 542)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 28)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 559)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 28)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 560)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 28)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 542)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 29)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 543)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 29)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 560)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 29)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 561)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 29)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 558)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 30)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 559)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 30)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 576)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 30)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 577)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 30)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 559)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 31)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 560)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 31)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 577)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 31)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 578)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 31)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 560)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 32)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 561)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 32)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 578)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 32)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 579)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 32)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 576)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 33)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 577)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 33)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 594)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 33)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 595)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 33)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 577)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 34)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 578)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 34)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 595)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 34)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 596)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 34)]));
        conv2d_nchw_local[(ff_c_outer_inner * 4)] = (conv2d_nchw_local[(ff_c_outer_inner * 4)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 578)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 35)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 1)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 579)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 35)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 2)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 596)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 35)]));
        conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] = (conv2d_nchw_local[((ff_c_outer_inner * 4) + 3)] + (pad_temp_shared[((((rc_outer_inner * 720) + (((((int)threadIdx.x) & 31) >> 3) * 36)) + ((((int)threadIdx.x) & 7) * 2)) + 597)] * kernel_shared[(((((((int)threadIdx.x) >> 5) * 288) + (ff_c_outer_inner * 72)) + (rc_outer_inner * 36)) + 35)]));
      }
    }
  }
  for (int ff_inner = 0; ff_inner < 4; ++ff_inner) {
    for (int yy_inner = 0; yy_inner < 2; ++yy_inner) {
      for (int xx_inner = 0; xx_inner < 2; ++xx_inner) {
        conv2d_nchw[(((((((((((int)threadIdx.x) >> 5) * 200704) + (ff_inner * 50176)) + ((((int)blockIdx.x) / 14) * 1792)) + (((((int)threadIdx.x) & 31) >> 3) * 448)) + (yy_inner * 224)) + ((((int)blockIdx.x) % 14) * 16)) + ((((int)threadIdx.x) & 7) * 2)) + xx_inner)] = conv2d_nchw_local[(((ff_inner * 4) + (yy_inner * 2)) + xx_inner)];
      }
    }
  }
}


