#include "hip/hip_runtime.h"

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(256) candidate2(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nchw) {
  float conv2d_nchw_local[112];
  __shared__ float pad_temp_shared[4640];
  __shared__ float kernel_shared[4608];
  for (int yy_c_outer_inner_init = 0; yy_c_outer_inner_init < 2; ++yy_c_outer_inner_init) {
    conv2d_nchw_local[(yy_c_outer_inner_init * 28)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 56)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 4)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 60)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 8)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 64)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 12)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 68)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 16)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 72)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 20)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 76)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 24)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 80)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 1)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 57)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 5)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 61)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 9)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 65)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 13)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 69)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 17)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 73)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 21)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 77)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 25)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 81)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 2)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 58)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 6)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 62)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 10)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 66)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 14)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 70)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 18)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 74)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 22)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 78)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 26)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 82)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 3)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 59)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 7)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 63)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 11)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 67)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 15)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 71)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 19)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 75)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 23)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 79)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 27)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 28) + 83)] = 0.000000e+00f;
  }
  for (int rc_outer_outer = 0; rc_outer_outer < 16; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[((int)threadIdx.x)] = ((((10 <= ((int)threadIdx.x)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10)) < 57)) ? data[(((((rc_outer_outer * 25088) + ((((int)threadIdx.x) / 10) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((int)threadIdx.x) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 256)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10)) < 57)) ? data[(((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 256) / 10) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 6) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 512)] = (((((5 <= (((((int)threadIdx.x) >> 1) + 256) % 290)) && (((((int)threadIdx.x) + 512) % 580) < 570)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 512) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 256) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 2) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 768)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 768) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 94) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 8) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1024)] = (((((5 <= (((((int)threadIdx.x) >> 1) + 222) % 290)) && (((((int)threadIdx.x) + 444) % 580) < 570)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 4) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 4) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1024) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 222) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 4) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1280)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1280) / 580) * 3136)) + (((((int)threadIdx.x) / 10) + 12) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((int)threadIdx.x) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1536)] = (((((5 <= (((((int)threadIdx.x) >> 1) + 188) % 290)) && (((((int)threadIdx.x) + 376) % 580) < 570)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1536) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 188) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 6) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1792)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1792) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 26) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 2) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2048)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2048) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 154) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 8) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2304)] = (((((5 <= (((((int)threadIdx.x) >> 1) + 282) % 290)) && (((((int)threadIdx.x) + 564) % 580) < 570)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 4) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 4) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2304) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 282) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 4) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2560)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2560) / 580) * 3136)) + (((((int)threadIdx.x) / 10) + 24) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((int)threadIdx.x) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2816)] = (((((5 <= (((((int)threadIdx.x) >> 1) + 248) % 290)) && (((((int)threadIdx.x) + 496) % 580) < 570)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2816) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 248) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 6) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 3072)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 3072) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 86) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 2) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 3328)] = (((((5 <= (((((int)threadIdx.x) >> 1) + 214) % 290)) && (((((int)threadIdx.x) + 428) % 580) < 570)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 3328) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 214) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 8) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 3584)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 4) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 4) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 3584) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 52) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 4) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 3840)] = (((((1 <= (((((int)threadIdx.x) / 10) + 36) % 58)) && (((((int)threadIdx.x) + 360) % 580) < 570)) && (1 <= (((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + (((int)threadIdx.x) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 3840) / 580) * 3136)) + ((((((int)threadIdx.x) / 10) + 36) % 58) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((int)threadIdx.x) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 4096)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 6) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 4096) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 18) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 6) % 10)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 4352)] = (((1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 2) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 4352) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 146) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 2) % 10)) - 57)] : 0.000000e+00f);
    if (((int)threadIdx.x) < 32) {
      pad_temp_shared[(((int)threadIdx.x) + 4608)] = ((((((int)threadIdx.x) < 22) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10)))) && ((((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) + 8) % 10)) < 57)) ? data[((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 4608) / 580) * 3136)) + (((((((int)threadIdx.x) >> 1) + 274) % 290) / 5) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) + 8) % 10)) - 57)] : 0.000000e+00f);
    }
    kernel_shared[((int)threadIdx.x)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + ((((int)threadIdx.x) / 72) * 1152)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72))];
    kernel_shared[(((int)threadIdx.x) + 256)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 256) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 40) % 72))];
    kernel_shared[(((int)threadIdx.x) + 512)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 512) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 8) % 72))];
    kernel_shared[(((int)threadIdx.x) + 768)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 768) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 48) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1024)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 1024) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 16) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1280)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 1280) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 56) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1536)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 1536) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 24) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1792)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 1792) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 64) % 72))];
    kernel_shared[(((int)threadIdx.x) + 2048)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 2048) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 32) % 72))];
    kernel_shared[(((int)threadIdx.x) + 2304)] = kernel[((((((((int)blockIdx.x) / 7) * 73728) + ((((int)threadIdx.x) / 72) * 1152)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)) + 36864)];
    kernel_shared[(((int)threadIdx.x) + 2560)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 2560) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 40) % 72))];
    kernel_shared[(((int)threadIdx.x) + 2816)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 2816) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 8) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3072)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 3072) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 48) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3328)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 3328) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 16) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3584)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 3584) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 56) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3840)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 3840) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 24) % 72))];
    kernel_shared[(((int)threadIdx.x) + 4096)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 4096) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 64) % 72))];
    kernel_shared[(((int)threadIdx.x) + 4352)] = kernel[(((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 4352) / 72) * 1152)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 32) % 72))];
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 8; ++rc_outer_inner) {
      for (int ry_outer_inner = 0; ry_outer_inner < 3; ++ry_outer_inner) {
        for (int yy_c_outer_inner = 0; yy_c_outer_inner < 2; ++yy_c_outer_inner) {
          for (int xx_c_outer_inner = 0; xx_c_outer_inner < 4; ++xx_c_outer_inner) {
            conv2d_nchw_local[((yy_c_outer_inner * 28) + xx_c_outer_inner)] = (conv2d_nchw_local[((yy_c_outer_inner * 28) + xx_c_outer_inner)] + (pad_temp_shared[((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 56)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 56)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 280)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 4)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 4)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 10)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 60)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 60)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 290)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 8)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 8)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 20)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 64)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 64)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 300)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 12)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 12)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 30)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 68)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 68)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 310)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 16)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 16)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 40)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 72)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 72)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 320)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 20)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 20)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 50)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 76)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 76)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 330)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 24)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 24)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 60)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 80)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 80)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 340)] * kernel_shared[((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3))]));
            conv2d_nchw_local[((yy_c_outer_inner * 28) + xx_c_outer_inner)] = (conv2d_nchw_local[((yy_c_outer_inner * 28) + xx_c_outer_inner)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 1)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 56)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 56)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 281)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 4)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 4)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 11)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 60)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 60)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 291)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 8)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 8)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 21)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 64)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 64)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 301)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 12)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 12)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 31)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 68)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 68)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 311)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 16)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 16)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 41)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 72)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 72)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 321)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 20)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 20)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 51)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 76)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 76)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 331)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 24)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 24)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 61)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 80)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 80)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 341)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 1)]));
            conv2d_nchw_local[((yy_c_outer_inner * 28) + xx_c_outer_inner)] = (conv2d_nchw_local[((yy_c_outer_inner * 28) + xx_c_outer_inner)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 2)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 56)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 56)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 282)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 4)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 4)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 12)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 60)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 60)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 292)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 8)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 8)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 22)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 64)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 64)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 302)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 12)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 12)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 32)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 68)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 68)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 312)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 16)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 16)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 42)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 72)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 72)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 322)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 20)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 20)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 52)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 76)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 76)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 332)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 24)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 24)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 62)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
            conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 80)] = (conv2d_nchw_local[(((yy_c_outer_inner * 28) + xx_c_outer_inner) + 80)] + (pad_temp_shared[(((((((rc_outer_inner * 580) + (((((int)threadIdx.x) & 3) >> 1) * 140)) + (yy_c_outer_inner * 70)) + (ry_outer_inner * 10)) + ((((int)threadIdx.x) & 1) * 4)) + xx_c_outer_inner) + 342)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + 2)]));
          }
        }
      }
    }
  }
  for (int yy_inner = 0; yy_inner < 14; ++yy_inner) {
    for (int xx_inner = 0; xx_inner < 4; ++xx_inner) {
      conv2d_nchw[((((((((((int)blockIdx.x) / 7) * 200704) + ((((int)threadIdx.x) >> 2) * 3136)) + (((((int)threadIdx.x) & 3) >> 1) * 784)) + (yy_inner * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) & 1) * 4)) + xx_inner)] = conv2d_nchw_local[((yy_inner * 4) + xx_inner)];
      conv2d_nchw[(((((((((((int)blockIdx.x) / 7) * 200704) + ((((int)threadIdx.x) >> 2) * 3136)) + (((((int)threadIdx.x) & 3) >> 1) * 784)) + (yy_inner * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) & 1) * 4)) + xx_inner) + 1568)] = conv2d_nchw_local[(((yy_inner * 4) + xx_inner) + 56)];
    }
  }
}


