
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(256) candidate0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nchw) {
  float conv2d_nchw_local[4];
  __shared__ float pad_temp_shared[648];
  __shared__ float kernel_shared[4608];
  conv2d_nchw_local[0] = 0.000000e+00f;
  conv2d_nchw_local[2] = 0.000000e+00f;
  conv2d_nchw_local[1] = 0.000000e+00f;
  conv2d_nchw_local[3] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 8; ++rc_outer_outer) {
    __syncthreads();
    if (((int)threadIdx.x) < 108) {
      pad_temp_shared[(((int)threadIdx.x) * 6)] = (((1 <= ((((((int)blockIdx.x) % 49) / 7) * 8) + (((((int)threadIdx.x) * 2) % 27) / 3))) && (1 <= (((((int)blockIdx.x) % 7) * 8) + ((((int)threadIdx.x) * 6) % 9)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) * 2) / 27) * 3136)) + (((((int)blockIdx.x) % 49) / 7) * 448)) + ((((((int)threadIdx.x) * 2) % 27) / 3) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + ((((int)threadIdx.x) * 6) % 9)) - 57)] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 108) {
      pad_temp_shared[((((int)threadIdx.x) * 6) + 1)] = (((1 <= ((((((int)blockIdx.x) % 49) / 7) * 8) + (((((int)threadIdx.x) * 2) % 27) / 3))) && (1 <= (((((int)blockIdx.x) % 7) * 8) + (((((int)threadIdx.x) * 6) + 1) % 9)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) * 2) / 27) * 3136)) + (((((int)blockIdx.x) % 49) / 7) * 448)) + ((((((int)threadIdx.x) * 2) % 27) / 3) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((((int)threadIdx.x) * 6) + 1) % 9)) - 57)] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 108) {
      pad_temp_shared[((((int)threadIdx.x) * 6) + 2)] = (((1 <= ((((((int)blockIdx.x) % 49) / 7) * 8) + (((((int)threadIdx.x) * 2) % 27) / 3))) && (1 <= (((((int)blockIdx.x) % 7) * 8) + (((((int)threadIdx.x) * 6) + 2) % 9)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) * 2) / 27) * 3136)) + (((((int)blockIdx.x) % 49) / 7) * 448)) + ((((((int)threadIdx.x) * 2) % 27) / 3) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((((int)threadIdx.x) * 6) + 2) % 9)) - 57)] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 108) {
      pad_temp_shared[((((int)threadIdx.x) * 6) + 3)] = (((1 <= ((((((int)blockIdx.x) % 49) / 7) * 8) + ((((((int)threadIdx.x) * 2) + 1) % 27) / 3))) && (1 <= (((((int)blockIdx.x) % 7) * 8) + (((((int)threadIdx.x) * 6) + 3) % 9)))) ? data[(((((((rc_outer_outer * 25088) + ((((((int)threadIdx.x) * 2) + 1) / 27) * 3136)) + (((((int)blockIdx.x) % 49) / 7) * 448)) + (((((((int)threadIdx.x) * 2) + 1) % 27) / 3) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((((int)threadIdx.x) * 6) + 3) % 9)) - 57)] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 108) {
      pad_temp_shared[((((int)threadIdx.x) * 6) + 4)] = (((1 <= ((((((int)blockIdx.x) % 49) / 7) * 8) + ((((((int)threadIdx.x) * 2) + 1) % 27) / 3))) && (1 <= (((((int)blockIdx.x) % 7) * 8) + (((((int)threadIdx.x) * 6) + 4) % 9)))) ? data[(((((((rc_outer_outer * 25088) + ((((((int)threadIdx.x) * 2) + 1) / 27) * 3136)) + (((((int)blockIdx.x) % 49) / 7) * 448)) + (((((((int)threadIdx.x) * 2) + 1) % 27) / 3) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((((int)threadIdx.x) * 6) + 4) % 9)) - 57)] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 108) {
      pad_temp_shared[((((int)threadIdx.x) * 6) + 5)] = (((1 <= ((((((int)blockIdx.x) % 49) / 7) * 8) + ((((((int)threadIdx.x) * 2) + 1) % 27) / 3))) && (1 <= (((((int)blockIdx.x) % 7) * 8) + (((((int)threadIdx.x) * 6) + 5) % 9)))) ? data[(((((((rc_outer_outer * 25088) + ((((((int)threadIdx.x) * 2) + 1) / 27) * 3136)) + (((((int)blockIdx.x) % 49) / 7) * 448)) + (((((((int)threadIdx.x) * 2) + 1) % 27) / 3) * 56)) + ((((int)blockIdx.x) % 7) * 8)) + (((((int)threadIdx.x) * 6) + 5) % 9)) - 57)] : 0.000000e+00f);
    }
    kernel_shared[((int)threadIdx.x)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72))];
    kernel_shared[(((int)threadIdx.x) + 256)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 256) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 40) % 72))];
    kernel_shared[(((int)threadIdx.x) + 512)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 512) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 8) % 72))];
    kernel_shared[(((int)threadIdx.x) + 768)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 768) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 48) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1024)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 1024) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 16) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1280)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 1280) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 56) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1536)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 1536) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 24) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1792)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 1792) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 64) % 72))];
    kernel_shared[(((int)threadIdx.x) + 2048)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 2048) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 32) % 72))];
    kernel_shared[(((int)threadIdx.x) + 2304)] = kernel[((((((((int)blockIdx.x) / 49) * 36864) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)) + 18432)];
    kernel_shared[(((int)threadIdx.x) + 2560)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 2560) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 40) % 72))];
    kernel_shared[(((int)threadIdx.x) + 2816)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 2816) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 8) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3072)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 3072) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 48) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3328)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 3328) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 16) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3584)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 3584) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 56) % 72))];
    kernel_shared[(((int)threadIdx.x) + 3840)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 3840) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 24) % 72))];
    kernel_shared[(((int)threadIdx.x) + 4096)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 4096) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 64) % 72))];
    kernel_shared[(((int)threadIdx.x) + 4352)] = kernel[(((((((int)blockIdx.x) / 49) * 36864) + (((((int)threadIdx.x) + 4352) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 32) % 72))];
    __syncthreads();
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2))] * kernel_shared[((((int)threadIdx.x) >> 3) * 144)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 4)] * kernel_shared[((((int)threadIdx.x) >> 3) * 144)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2))] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 72)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 4)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 72)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 81)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 9)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 85)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 9)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 81)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 81)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 85)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 81)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 1)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 1)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 5)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 1)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 1)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 73)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 5)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 73)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 82)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 10)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 86)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 10)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 82)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 82)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 86)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 82)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 2)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 2)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 6)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 2)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 2)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 74)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 6)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 74)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 83)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 11)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 87)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 11)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 83)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 83)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 87)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 83)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 9)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 3)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 13)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 3)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 9)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 75)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 13)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 75)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 90)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 12)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 94)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 12)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 90)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 84)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 94)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 84)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 10)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 4)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 14)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 4)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 10)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 76)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 14)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 76)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 91)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 13)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 95)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 13)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 91)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 85)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 95)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 85)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 11)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 5)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 15)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 5)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 11)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 77)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 15)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 77)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 92)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 14)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 96)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 14)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 92)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 86)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 96)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 86)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 18)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 6)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 22)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 6)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 18)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 78)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 22)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 78)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 99)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 15)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 103)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 15)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 99)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 87)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 103)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 87)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 19)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 7)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 23)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 7)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 19)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 79)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 23)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 79)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 100)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 16)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 104)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 16)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 100)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 88)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 104)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 88)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 20)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 8)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 24)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 8)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 20)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 80)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 24)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 80)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 101)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 17)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 105)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 17)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 101)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 89)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 105)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 89)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 162)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 18)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 166)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 18)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 162)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 90)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 166)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 90)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 243)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 27)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 247)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 27)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 243)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 99)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 247)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 99)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 163)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 19)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 167)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 19)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 163)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 91)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 167)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 91)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 244)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 28)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 248)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 28)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 244)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 100)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 248)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 100)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 164)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 20)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 168)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 20)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 164)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 92)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 168)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 92)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 245)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 29)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 249)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 29)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 245)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 101)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 249)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 101)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 171)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 21)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 175)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 21)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 171)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 93)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 175)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 93)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 252)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 30)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 256)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 30)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 252)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 102)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 256)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 102)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 172)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 22)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 176)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 22)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 172)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 94)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 176)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 94)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 253)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 31)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 257)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 31)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 253)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 103)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 257)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 103)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 173)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 23)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 177)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 23)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 173)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 95)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 177)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 95)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 254)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 32)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 258)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 32)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 254)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 104)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 258)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 104)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 180)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 24)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 184)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 24)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 180)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 96)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 184)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 96)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 261)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 33)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 265)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 33)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 261)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 105)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 265)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 105)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 181)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 25)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 185)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 25)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 181)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 97)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 185)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 97)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 262)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 34)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 266)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 34)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 262)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 106)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 266)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 106)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 182)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 26)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 186)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 26)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 182)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 98)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 186)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 98)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 263)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 35)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 267)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 35)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 263)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 107)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 267)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 107)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 324)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 36)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 328)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 36)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 324)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 108)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 328)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 108)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 405)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 45)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 409)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 45)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 405)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 117)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 409)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 117)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 325)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 37)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 329)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 37)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 325)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 109)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 329)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 109)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 406)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 46)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 410)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 46)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 406)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 118)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 410)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 118)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 326)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 38)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 330)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 38)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 326)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 110)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 330)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 110)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 407)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 47)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 411)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 47)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 407)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 119)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 411)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 119)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 333)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 39)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 337)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 39)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 333)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 111)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 337)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 111)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 414)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 48)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 418)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 48)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 414)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 120)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 418)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 120)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 334)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 40)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 338)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 40)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 334)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 112)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 338)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 112)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 415)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 49)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 419)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 49)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 415)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 121)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 419)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 121)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 335)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 41)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 339)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 41)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 335)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 113)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 339)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 113)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 416)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 50)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 420)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 50)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 416)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 122)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 420)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 122)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 342)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 42)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 346)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 42)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 342)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 114)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 346)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 114)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 423)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 51)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 427)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 51)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 423)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 123)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 427)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 123)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 343)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 43)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 347)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 43)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 343)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 115)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 347)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 115)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 424)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 52)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 428)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 52)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 424)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 124)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 428)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 124)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 344)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 44)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 348)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 44)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 344)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 116)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 348)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 116)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 425)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 53)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 429)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 53)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 425)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 125)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 429)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 125)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 486)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 54)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 490)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 54)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 486)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 126)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 490)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 126)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 567)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 63)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 571)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 63)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 567)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 135)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 571)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 135)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 487)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 55)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 491)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 55)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 487)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 127)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 491)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 127)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 568)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 64)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 572)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 64)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 568)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 136)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 572)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 136)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 488)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 56)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 492)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 56)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 488)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 128)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 492)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 128)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 569)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 65)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 573)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 65)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 569)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 137)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 573)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 137)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 495)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 57)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 499)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 57)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 495)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 129)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 499)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 129)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 576)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 66)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 580)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 66)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 576)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 138)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 580)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 138)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 496)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 58)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 500)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 58)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 496)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 130)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 500)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 130)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 577)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 67)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 581)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 67)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 577)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 139)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 581)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 139)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 497)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 59)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 501)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 59)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 497)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 131)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 501)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 131)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 578)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 68)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 582)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 68)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 578)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 140)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 582)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 140)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 504)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 60)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 508)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 60)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 504)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 132)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 508)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 132)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 585)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 69)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 589)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 69)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 585)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 141)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 589)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 141)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 505)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 61)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 509)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 61)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 505)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 133)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 509)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 133)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 586)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 70)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 590)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 70)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 586)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 142)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 590)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 142)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 506)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 62)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 510)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 62)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 506)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 134)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 510)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 134)]));
    conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 587)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 71)]));
    conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 591)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 71)]));
    conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 587)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 143)]));
    conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((((int)threadIdx.x) & 7) >> 1) * 18) + ((((int)threadIdx.x) & 1) * 2)) + 591)] * kernel_shared[(((((int)threadIdx.x) >> 3) * 144) + 143)]));
  }
  for (int ff_inner = 0; ff_inner < 2; ++ff_inner) {
    conv2d_nchw[((((((((((int)blockIdx.x) / 49) * 50176) + ((((int)threadIdx.x) >> 3) * 1568)) + (ff_inner * 784)) + (((((int)blockIdx.x) % 49) / 7) * 112)) + (((((int)threadIdx.x) & 7) >> 1) * 28)) + ((((int)blockIdx.x) % 7) * 4)) + (((int)threadIdx.x) & 1))] = conv2d_nchw_local[ff_inner];
    conv2d_nchw[(((((((((((int)blockIdx.x) / 49) * 50176) + ((((int)threadIdx.x) >> 3) * 1568)) + (ff_inner * 784)) + (((((int)blockIdx.x) % 49) / 7) * 112)) + (((((int)threadIdx.x) & 7) >> 1) * 28)) + ((((int)blockIdx.x) % 7) * 4)) + (((int)threadIdx.x) & 1)) + 2)] = conv2d_nchw_local[(ff_inner + 2)];
  }
}


