
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(224) candidate3(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nchw) {
  float conv2d_nchw_local[14];
  __shared__ float pad_temp_shared[3480];
  __shared__ float kernel_shared[2304];
  conv2d_nchw_local[0] = 0.000000e+00f;
  conv2d_nchw_local[1] = 0.000000e+00f;
  conv2d_nchw_local[2] = 0.000000e+00f;
  conv2d_nchw_local[3] = 0.000000e+00f;
  conv2d_nchw_local[4] = 0.000000e+00f;
  conv2d_nchw_local[5] = 0.000000e+00f;
  conv2d_nchw_local[6] = 0.000000e+00f;
  conv2d_nchw_local[7] = 0.000000e+00f;
  conv2d_nchw_local[8] = 0.000000e+00f;
  conv2d_nchw_local[9] = 0.000000e+00f;
  conv2d_nchw_local[10] = 0.000000e+00f;
  conv2d_nchw_local[11] = 0.000000e+00f;
  conv2d_nchw_local[12] = 0.000000e+00f;
  conv2d_nchw_local[13] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 8; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[((int)threadIdx.x)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((int)threadIdx.x) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + (((int)threadIdx.x) % 29)))) ? data[((((((rc_outer_outer * 25088) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((int)threadIdx.x) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + (((int)threadIdx.x) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 224)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 224) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 21) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 224) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 224) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 21) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 448)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 13) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 13) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 448) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 13) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 13) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 672)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 237) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 5) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 672) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 237) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 5) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 896)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 26) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 26) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 896) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 26) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 26) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1120)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 250) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 18) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1120) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 250) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 18) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1344)] = ((1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 10) % 29))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1344) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 39) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 10) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1568)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 263) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 2) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1568) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 263) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 2) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1792)] = ((1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 23) % 29))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 1792) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 52) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 23) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2016)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 276) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 15) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2016) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 276) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 15) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2240)] = ((1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 7) % 29))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2240) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 65) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 7) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2464)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 289) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 28) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2464) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 289) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 28) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2688)] = ((1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 20) % 29))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2688) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 78) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 20) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2912)] = (((1 <= ((((((int)blockIdx.x) & 7) >> 1) * 14) + (((((int)threadIdx.x) + 302) % 435) / 29))) && (1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 12) % 29)))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 2912) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 302) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 12) % 29)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 3136)] = ((1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 4) % 29))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 3136) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 91) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 4) % 29)) - 57)] : 0.000000e+00f);
    if (((int)threadIdx.x) < 120) {
      pad_temp_shared[(((int)threadIdx.x) + 3360)] = ((1 <= (((((int)blockIdx.x) & 1) * 28) + ((((int)threadIdx.x) + 25) % 29))) ? data[(((((((rc_outer_outer * 25088) + (((((int)threadIdx.x) + 3360) / 435) * 3136)) + (((((int)blockIdx.x) & 7) >> 1) * 784)) + ((((((int)threadIdx.x) + 315) % 435) / 29) * 56)) + ((((int)blockIdx.x) & 1) * 28)) + ((((int)threadIdx.x) + 25) % 29)) - 57)] : 0.000000e+00f);
    }
    kernel_shared[((int)threadIdx.x)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72))];
    kernel_shared[(((int)threadIdx.x) + 224)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 224) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 8) % 72))];
    kernel_shared[(((int)threadIdx.x) + 448)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 448) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 16) % 72))];
    kernel_shared[(((int)threadIdx.x) + 672)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 672) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 24) % 72))];
    kernel_shared[(((int)threadIdx.x) + 896)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 896) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 32) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1120)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 1120) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 40) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1344)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 1344) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 48) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1568)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 1568) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 56) % 72))];
    kernel_shared[(((int)threadIdx.x) + 1792)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 1792) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 64) % 72))];
    kernel_shared[(((int)threadIdx.x) + 2016)] = kernel[((((((((int)blockIdx.x) >> 3) * 18432) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)) + 16128)];
    if (((int)threadIdx.x) < 64) {
      kernel_shared[(((int)threadIdx.x) + 2240)] = kernel[(((((((int)blockIdx.x) >> 3) * 18432) + (((((int)threadIdx.x) + 2240) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) + 8))];
    }
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 2; ++rc_outer_inner) {
      for (int ry_outer_inner = 0; ry_outer_inner < 3; ++ry_outer_inner) {
        for (int rx_outer_inner = 0; rx_outer_inner < 3; ++rx_outer_inner) {
          conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 2)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 435)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 437)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 870)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 872)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1305)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1307)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 4)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 6)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 439)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 441)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 874)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 876)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1309)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1311)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 8)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 10)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 443)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 445)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 878)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 880)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1313)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1315)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 12)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 14)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 447)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 449)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 882)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 884)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1317)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1319)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[8] = (conv2d_nchw_local[8] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 16)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[9] = (conv2d_nchw_local[9] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 18)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[8] = (conv2d_nchw_local[8] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 451)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[9] = (conv2d_nchw_local[9] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 453)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[8] = (conv2d_nchw_local[8] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 886)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[9] = (conv2d_nchw_local[9] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 888)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[8] = (conv2d_nchw_local[8] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1321)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[9] = (conv2d_nchw_local[9] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1323)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[10] = (conv2d_nchw_local[10] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 20)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[11] = (conv2d_nchw_local[11] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 22)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[10] = (conv2d_nchw_local[10] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 455)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[11] = (conv2d_nchw_local[11] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 457)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[10] = (conv2d_nchw_local[10] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 890)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[11] = (conv2d_nchw_local[11] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 892)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[10] = (conv2d_nchw_local[10] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1325)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[11] = (conv2d_nchw_local[11] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1327)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[12] = (conv2d_nchw_local[12] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 24)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[13] = (conv2d_nchw_local[13] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 26)] * kernel_shared[(((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          conv2d_nchw_local[12] = (conv2d_nchw_local[12] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 459)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[13] = (conv2d_nchw_local[13] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 461)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 9)]));
          conv2d_nchw_local[12] = (conv2d_nchw_local[12] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 894)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[13] = (conv2d_nchw_local[13] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 896)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 18)]));
          conv2d_nchw_local[12] = (conv2d_nchw_local[12] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1329)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
          conv2d_nchw_local[13] = (conv2d_nchw_local[13] + (pad_temp_shared[(((((rc_outer_inner * 1740) + ((((int)threadIdx.x) % 7) * 58)) + (ry_outer_inner * 29)) + rx_outer_inner) + 1331)] * kernel_shared[((((((((int)threadIdx.x) / 7) * 72) + (rc_outer_inner * 36)) + (ry_outer_inner * 3)) + rx_outer_inner) + 27)]));
        }
      }
    }
  }
  for (int xx_inner = 0; xx_inner < 14; ++xx_inner) {
    conv2d_nchw[(((((((((int)blockIdx.x) >> 3) * 25088) + ((((int)threadIdx.x) / 7) * 784)) + (((((int)blockIdx.x) & 7) >> 1) * 196)) + ((((int)threadIdx.x) % 7) * 28)) + ((((int)blockIdx.x) & 1) * 14)) + xx_inner)] = conv2d_nchw_local[xx_inner];
  }
}


