
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(256) candidate1(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute, float* __restrict__ bias) {
  float conv2d_nchw[98];
  __shared__ float pad_temp_shared[1024];
  __shared__ float kernel_shared[4608];
  for (int ff_outer_inner_init = 0; ff_outer_inner_init < 2; ++ff_outer_inner_init) {
    conv2d_nchw[(ff_outer_inner_init * 49)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 1)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 2)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 3)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 4)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 5)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 6)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 7)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 8)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 9)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 10)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 11)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 12)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 13)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 14)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 15)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 16)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 17)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 18)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 19)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 20)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 21)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 22)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 23)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 24)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 25)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 26)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 27)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 28)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 29)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 30)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 31)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 32)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 33)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 34)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 35)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 36)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 37)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 38)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 39)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 40)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 41)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 42)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 43)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 44)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 45)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 46)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 47)] = 0.000000e+00f;
    conv2d_nchw[((ff_outer_inner_init * 49) + 48)] = 0.000000e+00f;
  }
  for (int rc_outer_outer = 0; rc_outer_outer < 16; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[((int)threadIdx.x)] = (((((1 <= (((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4))) && ((((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4)) < 57)) && (1 <= (((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)))) && ((((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)) < 57)) ? data[((((((rc_outer_outer * 12544) + ((((int)blockIdx.x) >> 2) * 784)) + ((((int)threadIdx.x) >> 4) * 56)) + ((((int)blockIdx.x) & 3) * 14)) + (((int)threadIdx.x) & 15)) - 57)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 256)] = (((((1 <= (((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4))) && ((((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4)) < 57)) && (1 <= (((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)))) && ((((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)) < 57)) ? data[((((((rc_outer_outer * 12544) + ((((int)blockIdx.x) >> 2) * 784)) + ((((int)threadIdx.x) >> 4) * 56)) + ((((int)blockIdx.x) & 3) * 14)) + (((int)threadIdx.x) & 15)) + 3079)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 512)] = (((((1 <= (((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4))) && ((((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4)) < 57)) && (1 <= (((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)))) && ((((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)) < 57)) ? data[((((((rc_outer_outer * 12544) + ((((int)blockIdx.x) >> 2) * 784)) + ((((int)threadIdx.x) >> 4) * 56)) + ((((int)blockIdx.x) & 3) * 14)) + (((int)threadIdx.x) & 15)) + 6215)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 768)] = (((((1 <= (((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4))) && ((((((int)blockIdx.x) >> 2) * 14) + (((int)threadIdx.x) >> 4)) < 57)) && (1 <= (((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)))) && ((((((int)blockIdx.x) & 3) * 14) + (((int)threadIdx.x) & 15)) < 57)) ? data[((((((rc_outer_outer * 12544) + ((((int)blockIdx.x) >> 2) * 784)) + ((((int)threadIdx.x) >> 4) * 56)) + ((((int)blockIdx.x) & 3) * 14)) + (((int)threadIdx.x) & 15)) + 9351)] : 0.000000e+00f);
    kernel_shared[((int)threadIdx.x)] = kernel[((((((int)threadIdx.x) / 36) * 576) + (rc_outer_outer * 36)) + (((int)threadIdx.x) % 36))];
    kernel_shared[(((int)threadIdx.x) + 256)] = kernel[(((((((int)threadIdx.x) + 256) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 4) % 36))];
    kernel_shared[(((int)threadIdx.x) + 512)] = kernel[(((((((int)threadIdx.x) + 512) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 8) % 36))];
    kernel_shared[(((int)threadIdx.x) + 768)] = kernel[(((((((int)threadIdx.x) + 768) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 12) % 36))];
    kernel_shared[(((int)threadIdx.x) + 1024)] = kernel[(((((((int)threadIdx.x) + 1024) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 16) % 36))];
    kernel_shared[(((int)threadIdx.x) + 1280)] = kernel[(((((((int)threadIdx.x) + 1280) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 20) % 36))];
    kernel_shared[(((int)threadIdx.x) + 1536)] = kernel[(((((((int)threadIdx.x) + 1536) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 24) % 36))];
    kernel_shared[(((int)threadIdx.x) + 1792)] = kernel[(((((((int)threadIdx.x) + 1792) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 28) % 36))];
    kernel_shared[(((int)threadIdx.x) + 2048)] = kernel[(((((((int)threadIdx.x) + 2048) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 32) % 36))];
    kernel_shared[(((int)threadIdx.x) + 2304)] = kernel[(((((((int)threadIdx.x) / 36) * 576) + (rc_outer_outer * 36)) + (((int)threadIdx.x) % 36)) + 36864)];
    kernel_shared[(((int)threadIdx.x) + 2560)] = kernel[(((((((int)threadIdx.x) + 2560) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 4) % 36))];
    kernel_shared[(((int)threadIdx.x) + 2816)] = kernel[(((((((int)threadIdx.x) + 2816) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 8) % 36))];
    kernel_shared[(((int)threadIdx.x) + 3072)] = kernel[(((((((int)threadIdx.x) + 3072) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 12) % 36))];
    kernel_shared[(((int)threadIdx.x) + 3328)] = kernel[(((((((int)threadIdx.x) + 3328) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 16) % 36))];
    kernel_shared[(((int)threadIdx.x) + 3584)] = kernel[(((((((int)threadIdx.x) + 3584) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 20) % 36))];
    kernel_shared[(((int)threadIdx.x) + 3840)] = kernel[(((((((int)threadIdx.x) + 3840) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 24) % 36))];
    kernel_shared[(((int)threadIdx.x) + 4096)] = kernel[(((((((int)threadIdx.x) + 4096) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 28) % 36))];
    kernel_shared[(((int)threadIdx.x) + 4352)] = kernel[(((((((int)threadIdx.x) + 4352) / 36) * 576) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 32) % 36))];
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 2; ++rc_outer_inner) {
      for (int ff_outer_inner = 0; ff_outer_inner < 2; ++ff_outer_inner) {
        for (int yy_outer_inner = 0; yy_outer_inner < 7; ++yy_outer_inner) {
          for (int rc_inner = 0; rc_inner < 2; ++rc_inner) {
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[(((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7))] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9))]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 1)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9))]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 2)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9))]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 3)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9))]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 4)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9))]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 5)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9))]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 6)] * kernel_shared[(((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9))]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 1)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 1)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 2)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 1)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 3)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 1)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 4)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 1)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 5)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 1)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 6)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 1)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 7)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 1)]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 2)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 2)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 3)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 2)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 4)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 2)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 5)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 2)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 6)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 2)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 7)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 2)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 8)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 2)]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 16)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 3)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 17)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 3)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 18)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 3)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 19)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 3)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 20)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 3)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 21)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 3)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 22)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 3)]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 17)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 4)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 18)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 4)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 19)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 4)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 20)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 4)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 21)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 4)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 22)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 4)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 23)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 4)]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 18)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 5)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 19)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 5)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 20)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 5)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 21)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 5)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 22)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 5)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 23)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 5)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 24)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 5)]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 32)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 6)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 33)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 6)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 34)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 6)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 35)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 6)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 36)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 6)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 37)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 6)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 38)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 6)]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 33)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 7)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 34)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 7)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 35)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 7)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 36)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 7)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 37)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 7)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 38)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 7)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 39)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 7)]));
            conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] = (conv2d_nchw[((ff_outer_inner * 49) + (yy_outer_inner * 7))] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 34)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 8)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 1)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 35)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 8)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 2)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 36)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 8)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 3)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 37)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 8)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 4)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 38)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 8)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 5)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 39)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 8)]));
            conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] = (conv2d_nchw[(((ff_outer_inner * 49) + (yy_outer_inner * 7)) + 6)] + (pad_temp_shared[((((((rc_outer_inner * 512) + (rc_inner * 256)) + (((((int)threadIdx.x) & 3) >> 1) * 112)) + (yy_outer_inner * 16)) + ((((int)threadIdx.x) & 1) * 7)) + 40)] * kernel_shared[((((((((int)threadIdx.x) >> 2) * 72) + (ff_outer_inner * 36)) + (rc_outer_inner * 18)) + (rc_inner * 9)) + 8)]));
          }
        }
      }
    }
  }
  for (int i1_inner = 0; i1_inner < 2; ++i1_inner) {
    for (int i2_inner = 0; i2_inner < 7; ++i2_inner) {
      for (int i3_inner = 0; i3_inner < 7; ++i3_inner) {
        compute[(((((((((((int)threadIdx.x) >> 2) * 6272) + (i1_inner * 3136)) + ((((int)blockIdx.x) >> 2) * 784)) + (((((int)threadIdx.x) & 3) >> 1) * 392)) + (i2_inner * 56)) + ((((int)blockIdx.x) & 3) * 14)) + ((((int)threadIdx.x) & 1) * 7)) + i3_inner)] = max((conv2d_nchw[(((i1_inner * 49) + (i2_inner * 7)) + i3_inner)] + bias[(((((int)threadIdx.x) >> 2) * 2) + i1_inner)]), 0.000000e+00f);
      }
    }
  }
}


