#include "hip/hip_runtime.h"

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(112) candidate5(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nchw) {
  float conv2d_nchw_local[8];
  __shared__ float pad_temp_shared[448];
  __shared__ float kernel_shared[768];
  conv2d_nchw_local[0] = 0.000000e+00f;
  conv2d_nchw_local[4] = 0.000000e+00f;
  conv2d_nchw_local[1] = 0.000000e+00f;
  conv2d_nchw_local[5] = 0.000000e+00f;
  conv2d_nchw_local[2] = 0.000000e+00f;
  conv2d_nchw_local[6] = 0.000000e+00f;
  conv2d_nchw_local[3] = 0.000000e+00f;
  conv2d_nchw_local[7] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 32; ++rc_outer_outer) {
    for (int rx_outer_outer = 0; rx_outer_outer < 3; ++rx_outer_outer) {
      __syncthreads();
      pad_temp_shared[((int)threadIdx.x)] = (((((1 <= (((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14))) && ((((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14)) < 15)) && (1 <= (rx_outer_outer + (((int)threadIdx.x) % 14)))) && ((rx_outer_outer + (((int)threadIdx.x) % 14)) < 15)) ? data[((((((rc_outer_outer * 1568) + ((((int)threadIdx.x) / 56) * 196)) + ((((int)blockIdx.x) % 7) * 28)) + rx_outer_outer) + (((int)threadIdx.x) % 56)) - 15)] : 0.000000e+00f);
      pad_temp_shared[(((int)threadIdx.x) + 112)] = (((((1 <= (((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14))) && ((((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14)) < 15)) && (1 <= (rx_outer_outer + (((int)threadIdx.x) % 14)))) && ((rx_outer_outer + (((int)threadIdx.x) % 14)) < 15)) ? data[((((((rc_outer_outer * 1568) + ((((int)threadIdx.x) / 56) * 196)) + ((((int)blockIdx.x) % 7) * 28)) + rx_outer_outer) + (((int)threadIdx.x) % 56)) + 377)] : 0.000000e+00f);
      pad_temp_shared[(((int)threadIdx.x) + 224)] = (((((1 <= (((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14))) && ((((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14)) < 15)) && (1 <= (rx_outer_outer + (((int)threadIdx.x) % 14)))) && ((rx_outer_outer + (((int)threadIdx.x) % 14)) < 15)) ? data[((((((rc_outer_outer * 1568) + ((((int)threadIdx.x) / 56) * 196)) + ((((int)blockIdx.x) % 7) * 28)) + rx_outer_outer) + (((int)threadIdx.x) % 56)) + 769)] : 0.000000e+00f);
      pad_temp_shared[(((int)threadIdx.x) + 336)] = (((((1 <= (((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14))) && ((((((int)blockIdx.x) % 7) * 2) + ((((int)threadIdx.x) % 56) / 14)) < 15)) && (1 <= (rx_outer_outer + (((int)threadIdx.x) % 14)))) && ((rx_outer_outer + (((int)threadIdx.x) % 14)) < 15)) ? data[((((((rc_outer_outer * 1568) + ((((int)threadIdx.x) / 56) * 196)) + ((((int)blockIdx.x) % 7) * 28)) + rx_outer_outer) + (((int)threadIdx.x) % 56)) + 1161)] : 0.000000e+00f);
      kernel_shared[((int)threadIdx.x)] = kernel[((((((((int)blockIdx.x) / 7) * 73728) + ((((int)threadIdx.x) / 24) * 2304)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) % 24) * 3)) + rx_outer_outer)];
      kernel_shared[(((int)threadIdx.x) + 112)] = kernel[((((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 112) / 24) * 2304)) + (rc_outer_outer * 72)) + (((((int)threadIdx.x) + 16) % 24) * 3)) + rx_outer_outer)];
      kernel_shared[(((int)threadIdx.x) + 224)] = kernel[((((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 224) / 24) * 2304)) + (rc_outer_outer * 72)) + (((((int)threadIdx.x) + 8) % 24) * 3)) + rx_outer_outer)];
      kernel_shared[(((int)threadIdx.x) + 336)] = kernel[(((((((((int)blockIdx.x) / 7) * 73728) + ((((int)threadIdx.x) / 24) * 2304)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) % 24) * 3)) + rx_outer_outer) + 32256)];
      kernel_shared[(((int)threadIdx.x) + 448)] = kernel[((((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 448) / 24) * 2304)) + (rc_outer_outer * 72)) + (((((int)threadIdx.x) + 16) % 24) * 3)) + rx_outer_outer)];
      kernel_shared[(((int)threadIdx.x) + 560)] = kernel[((((((((int)blockIdx.x) / 7) * 73728) + (((((int)threadIdx.x) + 560) / 24) * 2304)) + (rc_outer_outer * 72)) + (((((int)threadIdx.x) + 8) % 24) * 3)) + rx_outer_outer)];
      if (((int)threadIdx.x) < 96) {
        kernel_shared[(((int)threadIdx.x) + 672)] = kernel[(((((((((int)blockIdx.x) / 7) * 73728) + ((((int)threadIdx.x) / 24) * 2304)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) % 24) * 3)) + rx_outer_outer) + 64512)];
      }
      __syncthreads();
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[(((int)threadIdx.x) % 14)] * kernel_shared[((((int)threadIdx.x) / 14) * 96)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[((((int)threadIdx.x) / 14) * 96)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 1)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 1)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 2)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 42)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 2)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 56)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 3)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 3)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 4)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 4)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 5)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 98)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 5)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 112)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 6)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 6)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 7)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 7)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 8)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 154)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 8)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 168)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 9)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 9)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 10)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 10)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 11)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 210)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 11)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[(((int)threadIdx.x) % 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 24)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 24)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 25)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 25)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 26)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 42)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 26)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 56)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 27)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 27)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 28)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 28)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 29)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 98)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 29)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 112)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 30)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 30)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 31)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 31)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 32)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 154)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 32)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 168)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 33)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 33)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 34)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 34)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 35)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 210)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 35)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[(((int)threadIdx.x) % 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 48)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 48)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 49)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 49)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 50)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 42)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 50)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 56)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 51)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 51)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 52)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 52)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 53)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 98)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 53)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 112)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 54)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 54)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 55)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 55)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 56)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 154)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 56)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 168)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 57)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 57)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 58)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 58)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 59)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 210)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 59)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[(((int)threadIdx.x) % 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 72)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 72)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 14)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 73)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 73)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 28)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 74)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 42)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 74)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 56)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 75)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 75)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 70)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 76)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 76)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 84)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 77)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 98)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 77)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 112)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 78)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 78)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 126)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 79)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 79)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 140)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 80)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 154)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 80)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 168)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 81)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 81)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 182)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 82)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 82)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 196)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 83)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 210)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 83)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 224)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 12)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 12)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 13)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 13)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 14)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 266)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 14)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 280)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 15)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 15)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 16)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 16)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 17)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 322)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 17)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 336)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 18)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 18)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 19)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 19)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 20)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 378)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 20)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 392)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 21)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 21)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 22)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 22)]));
      conv2d_nchw_local[0] = (conv2d_nchw_local[0] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 23)]));
      conv2d_nchw_local[4] = (conv2d_nchw_local[4] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 434)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 23)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 224)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 36)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 36)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 37)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 37)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 38)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 266)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 38)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 280)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 39)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 39)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 40)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 40)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 41)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 322)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 41)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 336)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 42)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 42)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 43)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 43)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 44)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 378)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 44)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 392)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 45)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 45)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 46)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 46)]));
      conv2d_nchw_local[1] = (conv2d_nchw_local[1] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 47)]));
      conv2d_nchw_local[5] = (conv2d_nchw_local[5] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 434)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 47)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 224)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 60)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 60)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 61)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 61)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 62)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 266)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 62)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 280)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 63)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 63)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 64)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 64)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 65)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 322)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 65)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 336)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 66)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 66)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 67)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 67)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 68)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 378)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 68)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 392)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 69)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 69)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 70)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 70)]));
      conv2d_nchw_local[2] = (conv2d_nchw_local[2] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 71)]));
      conv2d_nchw_local[6] = (conv2d_nchw_local[6] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 434)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 71)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 224)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 84)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 84)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 238)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 85)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 85)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 252)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 86)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 266)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 86)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 280)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 87)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 87)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 294)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 88)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 88)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 308)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 89)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 322)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 89)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 336)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 90)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 90)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 350)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 91)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 91)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 364)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 92)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 378)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 92)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 392)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 93)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 93)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 406)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 94)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 94)]));
      conv2d_nchw_local[3] = (conv2d_nchw_local[3] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 420)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 95)]));
      conv2d_nchw_local[7] = (conv2d_nchw_local[7] + (pad_temp_shared[((((int)threadIdx.x) % 14) + 434)] * kernel_shared[(((((int)threadIdx.x) / 14) * 96) + 95)]));
    }
  }
  for (int ff_inner = 0; ff_inner < 4; ++ff_inner) {
    conv2d_nchw[((((((((int)blockIdx.x) / 7) * 6272) + ((((int)threadIdx.x) / 14) * 784)) + (ff_inner * 196)) + ((((int)blockIdx.x) % 7) * 28)) + (((int)threadIdx.x) % 14))] = conv2d_nchw_local[ff_inner];
    conv2d_nchw[(((((((((int)blockIdx.x) / 7) * 6272) + ((((int)threadIdx.x) / 14) * 784)) + (ff_inner * 196)) + ((((int)blockIdx.x) % 7) * 28)) + (((int)threadIdx.x) % 14)) + 14)] = conv2d_nchw_local[(ff_inner + 4)];
  }
}


