#include "hip/hip_runtime.h"

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(512) candidate3(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ conv2d_nchw) {
  float conv2d_nchw_local[98];
  __shared__ float pad_temp_shared[3600];
  __shared__ float kernel_shared[2304];
  for (int yy_c_outer_inner_init = 0; yy_c_outer_inner_init < 2; ++yy_c_outer_inner_init) {
    conv2d_nchw_local[(yy_c_outer_inner_init * 49)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 7)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 14)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 21)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 28)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 35)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 42)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 1)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 8)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 15)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 22)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 29)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 36)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 43)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 2)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 9)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 16)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 23)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 30)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 37)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 44)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 3)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 10)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 17)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 24)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 31)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 38)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 45)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 4)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 11)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 18)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 25)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 32)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 39)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 46)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 5)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 12)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 19)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 26)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 33)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 40)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 47)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 6)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 13)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 20)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 27)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 34)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 41)] = 0.000000e+00f;
    conv2d_nchw_local[((yy_c_outer_inner_init * 49) + 48)] = 0.000000e+00f;
  }
  for (int rc_outer_outer = 0; rc_outer_outer < 16; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[((int)threadIdx.x)] = ((((1 <= ((((((int)blockIdx.x) & 15) >> 2) * 28) + (((int)threadIdx.x) / 30))) && (1 <= (((((int)blockIdx.x) & 3) * 28) + (((int)threadIdx.x) % 30)))) && ((((((int)blockIdx.x) & 3) * 28) + (((int)threadIdx.x) % 30)) < 113)) ? data[((((((rc_outer_outer * 50176) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + ((((int)threadIdx.x) / 30) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + (((int)threadIdx.x) % 30)) - 113)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 512)] = (((((1 <= ((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 256) % 450) / 15))) && (((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 256) % 450) / 15)) < 113)) && (1 <= (((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 2) % 30)))) && ((((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 2) % 30)) < 113)) ? data[(((((((rc_outer_outer * 50176) + (((((int)threadIdx.x) + 512) / 900) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((((int)threadIdx.x) >> 1) + 256) % 450) / 15) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + ((((int)threadIdx.x) + 2) % 30)) - 113)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1024)] = (((1 <= (((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 4) % 30))) && ((((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 4) % 30)) < 113)) ? data[(((((((rc_outer_outer * 50176) + (((((int)threadIdx.x) + 1024) / 900) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((((int)threadIdx.x) >> 1) + 62) % 450) / 15) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + ((((int)threadIdx.x) + 4) % 30)) - 113)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 1536)] = (((((1 <= ((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 318) % 450) / 15))) && (((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 318) % 450) / 15)) < 113)) && (1 <= (((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 6) % 30)))) && ((((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 6) % 30)) < 113)) ? data[(((((((rc_outer_outer * 50176) + (((((int)threadIdx.x) + 1536) / 900) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((((int)threadIdx.x) >> 1) + 318) % 450) / 15) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + ((((int)threadIdx.x) + 6) % 30)) - 113)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2048)] = (((1 <= (((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 8) % 30))) && ((((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 8) % 30)) < 113)) ? data[(((((((rc_outer_outer * 50176) + (((((int)threadIdx.x) + 2048) / 900) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((((int)threadIdx.x) >> 1) + 124) % 450) / 15) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + ((((int)threadIdx.x) + 8) % 30)) - 113)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 2560)] = (((((1 <= ((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 380) % 450) / 15))) && (((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 380) % 450) / 15)) < 113)) && (1 <= (((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 10) % 30)))) && ((((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 10) % 30)) < 113)) ? data[(((((((rc_outer_outer * 50176) + (((((int)threadIdx.x) + 2560) / 900) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((((int)threadIdx.x) >> 1) + 380) % 450) / 15) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + ((((int)threadIdx.x) + 10) % 30)) - 113)] : 0.000000e+00f);
    pad_temp_shared[(((int)threadIdx.x) + 3072)] = ((((((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 186) % 450) / 15)) < 113) && (1 <= (((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 12) % 30)))) && ((((((int)blockIdx.x) & 3) * 28) + ((((int)threadIdx.x) + 12) % 30)) < 113)) ? data[(((((((rc_outer_outer * 50176) + (((((int)threadIdx.x) + 3072) / 900) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((((int)threadIdx.x) >> 1) + 186) % 450) / 15) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + ((((int)threadIdx.x) + 12) % 30)) - 113)] : 0.000000e+00f);
    if (((int)threadIdx.x) < 16) {
      pad_temp_shared[(((int)threadIdx.x) + 3584)] = (((((((((int)blockIdx.x) & 15) >> 2) * 28) + ((((((int)threadIdx.x) >> 1) + 442) % 450) / 15)) < 113) && ((((((int)blockIdx.x) & 3) * 28) + (((int)threadIdx.x) + 14)) < 113)) ? data[(((((((rc_outer_outer * 50176) + (((((int)threadIdx.x) + 3584) / 900) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((((int)threadIdx.x) >> 1) + 442) % 450) / 15) * 112)) + ((((int)blockIdx.x) & 3) * 28)) + (((int)threadIdx.x) + 14)) - 113)] : 0.000000e+00f);
    }
    kernel_shared[((int)threadIdx.x)] = kernel[(((((((int)blockIdx.x) >> 4) * 36864) + ((((int)threadIdx.x) / 36) * 576)) + (rc_outer_outer * 36)) + (((int)threadIdx.x) % 36))];
    kernel_shared[(((int)threadIdx.x) + 512)] = kernel[(((((((int)blockIdx.x) >> 4) * 36864) + (((((int)threadIdx.x) + 512) / 36) * 576)) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 8) % 36))];
    kernel_shared[(((int)threadIdx.x) + 1024)] = kernel[(((((((int)blockIdx.x) >> 4) * 36864) + (((((int)threadIdx.x) + 1024) / 36) * 576)) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 16) % 36))];
    kernel_shared[(((int)threadIdx.x) + 1536)] = kernel[(((((((int)blockIdx.x) >> 4) * 36864) + (((((int)threadIdx.x) + 1536) / 36) * 576)) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 24) % 36))];
    if (((int)threadIdx.x) < 256) {
      kernel_shared[(((int)threadIdx.x) + 2048)] = kernel[(((((((int)blockIdx.x) >> 4) * 36864) + (((((int)threadIdx.x) + 2048) / 36) * 576)) + (rc_outer_outer * 36)) + ((((int)threadIdx.x) + 32) % 36))];
    }
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 4; ++rc_outer_inner) {
      for (int ry_outer_inner = 0; ry_outer_inner < 3; ++ry_outer_inner) {
        for (int rx_outer_inner = 0; rx_outer_inner < 3; ++rx_outer_inner) {
          for (int yy_c_outer_inner = 0; yy_c_outer_inner < 2; ++yy_c_outer_inner) {
            conv2d_nchw_local[(yy_c_outer_inner * 49)] = (conv2d_nchw_local[(yy_c_outer_inner * 49)] + (pad_temp_shared[((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 7)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 7)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 30)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 14)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 14)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 60)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 21)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 21)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 90)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 28)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 28)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 120)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 35)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 35)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 150)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 42)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 42)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 180)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 1)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 1)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 1)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 8)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 8)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 31)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 15)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 15)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 61)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 22)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 22)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 91)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 29)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 29)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 121)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 36)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 36)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 151)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 43)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 43)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 181)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 2)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 2)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 2)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 9)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 9)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 32)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 16)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 16)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 62)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 23)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 23)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 92)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 30)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 30)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 122)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 37)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 37)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 152)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 44)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 44)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 182)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 3)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 3)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 3)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 10)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 10)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 33)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 17)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 17)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 63)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 24)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 24)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 93)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 31)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 31)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 123)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 38)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 38)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 153)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 45)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 45)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 183)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 4)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 4)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 4)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 11)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 11)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 34)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 18)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 18)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 64)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 25)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 25)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 94)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 32)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 32)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 124)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 39)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 39)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 154)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 46)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 46)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 184)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 5)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 5)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 5)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 12)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 12)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 35)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 19)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 19)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 65)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 26)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 26)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 95)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 33)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 33)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 125)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 40)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 40)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 155)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 47)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 47)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 185)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 6)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 6)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 6)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 13)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 13)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 36)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 20)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 20)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 66)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 27)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 27)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 96)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 34)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 34)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 126)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 41)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 41)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 156)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
            conv2d_nchw_local[((yy_c_outer_inner * 49) + 48)] = (conv2d_nchw_local[((yy_c_outer_inner * 49) + 48)] + (pad_temp_shared[(((((((rc_outer_inner * 900) + (((((int)threadIdx.x) & 7) >> 2) * 420)) + (yy_c_outer_inner * 210)) + (ry_outer_inner * 30)) + ((((int)threadIdx.x) & 3) * 7)) + rx_outer_inner) + 186)] * kernel_shared[(((((((int)threadIdx.x) >> 3) * 36) + (rc_outer_inner * 9)) + (ry_outer_inner * 3)) + rx_outer_inner)]));
          }
        }
      }
    }
  }
  for (int yy_inner = 0; yy_inner < 14; ++yy_inner) {
    for (int xx_inner = 0; xx_inner < 7; ++xx_inner) {
      conv2d_nchw[(((((((((((int)blockIdx.x) >> 4) * 802816) + ((((int)threadIdx.x) >> 3) * 12544)) + (((((int)blockIdx.x) & 15) >> 2) * 3136)) + (((((int)threadIdx.x) & 7) >> 2) * 1568)) + (yy_inner * 112)) + ((((int)blockIdx.x) & 3) * 28)) + ((((int)threadIdx.x) & 3) * 7)) + xx_inner)] = conv2d_nchw_local[((yy_inner * 7) + xx_inner)];
    }
  }
}


